language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

sudo: true

os:
  - linux
  - osx

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
